security.user.password: password
spring:
  jpa:
    showSql: true
  datasource:
    url: jdbc:mysql://localhost/jdbc
    username: dbuser
    password: dbpass
    tomcat:
      maxActive: 20
      initialSize: 5
      maxWait: 60000
      minIdle: 4
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
