spring:
  datasource:
    url: jdbc:mysql://localhost/jdbc
    username: dbuser
    password: dbpass
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 5
    maxWait: 60000
    minIdle: 5
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    # maxOpenPreparedStatements: 20
  jpa:
    showSql: true
    hibernate:
      ddlAuto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy

logging:
  level:
    root: WARN
  com:
    example:
      spring:
        jdbc:
          mapper: TRACE

# mybatis:
#   configLocation: classpath:mybatis-config-default.xml