security.user.password: password
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    showSql: true
  datasource:
    url: jdbc:mysql://localhost:8066/dbtest?useSSL=false
    username: root
    password: test
    tomcat:
      maxActive: 10
      initialSize: 5
      maxWait: 6000
      minIdle: 4
      timeBetweenEvictionRunsMillis: 6000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      logAbandoned: true
      removeAbandoned: true
